/****** Object:  Database [TIENDA SARA]    Script Date: 09/02/2024 01:05:47 a. m. ******/
CREATE DATABASE [TIENDA SARA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TIENDA SARA', FILENAME = N'C:\sqlData\TIENDA SARA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TIENDA SARA_log', FILENAME = N'C:\sqlData\TIENDA SARA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TIENDA SARA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TIENDA SARA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TIENDA SARA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TIENDA SARA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TIENDA SARA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TIENDA SARA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TIENDA SARA] SET ARITHABORT OFF 
GO
ALTER DATABASE [TIENDA SARA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TIENDA SARA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TIENDA SARA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TIENDA SARA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TIENDA SARA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TIENDA SARA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TIENDA SARA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TIENDA SARA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TIENDA SARA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TIENDA SARA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TIENDA SARA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TIENDA SARA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TIENDA SARA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TIENDA SARA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TIENDA SARA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TIENDA SARA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TIENDA SARA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TIENDA SARA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TIENDA SARA] SET  MULTI_USER 
GO
ALTER DATABASE [TIENDA SARA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TIENDA SARA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TIENDA SARA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TIENDA SARA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TIENDA SARA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TIENDA SARA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TIENDA SARA] SET QUERY_STORE = ON
GO
ALTER DATABASE [TIENDA SARA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
/****** Object:  Table [dbo].[Carrito]    Script Date: 09/02/2024 01:05:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carrito](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FolioVenta] [int] NOT NULL,
	[TotalCompra] [decimal](18, 2) NOT NULL,
	[Estatus] [int] NOT NULL,
	[Fecha] [date] NOT NULL,
 CONSTRAINT [PK_Carrito] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CarritoDetalle]    Script Date: 09/02/2024 01:05:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarritoDetalle](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdCarrito] [int] NOT NULL,
	[IdProducto] [int] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[SubTotal] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_CarritoDetalle] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categorias]    Script Date: 09/02/2024 01:05:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categorias](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Categorias] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Marcas]    Script Date: 09/02/2024 01:05:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Marcas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Marcas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Productos]    Script Date: 09/02/2024 01:05:48 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](max) NOT NULL,
	[Precio] [decimal](18, 2) NOT NULL,
	[Cantidad] [int] NOT NULL,
	[IdCategoria] [int] NOT NULL,
	[IdMarca] [int] NOT NULL,
 CONSTRAINT [PK_Productos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CarritoDetalle]  WITH CHECK ADD  CONSTRAINT [FK_CarritoDetalle_Carrito] FOREIGN KEY([IdCarrito])
REFERENCES [dbo].[Carrito] ([Id])
GO
ALTER TABLE [dbo].[CarritoDetalle] CHECK CONSTRAINT [FK_CarritoDetalle_Carrito]
GO
ALTER TABLE [dbo].[CarritoDetalle]  WITH CHECK ADD  CONSTRAINT [FK_CarritoDetalle_Productos] FOREIGN KEY([IdProducto])
REFERENCES [dbo].[Productos] ([Id])
GO
ALTER TABLE [dbo].[CarritoDetalle] CHECK CONSTRAINT [FK_CarritoDetalle_Productos]
GO
ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [FK_Productos_Categorias] FOREIGN KEY([IdCategoria])
REFERENCES [dbo].[Categorias] ([Id])
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Productos_Categorias]
GO
ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [FK_Productos_Marcas] FOREIGN KEY([IdMarca])
REFERENCES [dbo].[Marcas] ([Id])
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Productos_Marcas]
GO
ALTER DATABASE [TIENDA SARA] SET  READ_WRITE 
GO
